### ISSUE TITLE
Issue when commenting vim file

### ISSUE THREAD

**Issue by dpretet** [doums/coBra#1]
Hello,

I installed your plugin and it works well, I adopt :) I chased such one wince a while and it's a pleasure.

I just notice a small issue: when the comment start with `"`, commenting a line in a language like VimL leads to insert double `"` (for instance: " This is my line ").

Would it be possible to avoid this behavior? Insert just one `"` if it's a line start and the language uses `"` as comment symbol.

Damien

**Comment by doums** [comment]
Hi, I'm glad the plugin is useful to you! Thank.

I think this is a specific problem to vim "language" (I don't know of any other programming language that also uses `"` for comment syntax). Moreover in vim script, a comment can be put inline at the end of a line of code, so it's not as simple as you suggested to find a solution.

To keep the plugin clean and simple, I don't want to add any specific logic for edge cases.

To conclude, you can either set the variable `g:coBraPairs` and include a `vim` key without the pair `"` or, choose to keep it.

**Comment by dpretet** [comment]
I did try the solution you proposed but it doesn't work, maybe I didn't understand well the how to. FYI, I observed also a similar "issue" with SystemVerilog language which declares a define with back tick (`), not with a sharp (#) like like in C.

**Comment by doums** [comment]
Yes, I think you didn't understand me. If you prefer to disable the plugin features on the `"` pair, which will remove the "problem" you pointed, then add a vim key to the `g:coBraPairs` by omitting that pair:
```
let g:coBraPairs = {
      ...
      \ 'vim': [
      \    ["'", "'"],
      \    ['{', '}'],
      \    ['(', ')'],
      \    ['[', ']']
      \ ]
      \ }
```
Or continue to use the features on `"` and remove yourself the additional `"` character when you want to write a comment.
About SystemVerilog, I don't think it is a very popular and used language, so the problem remains specific. I think there are more cases like this, but they remain marginal cases.

**Comment by dpretet** [comment]
Thanks for the better explanation. So it's too restrictive, SystemVerilog is one of my principal language, I'll drop your plugin because of that, but thanks to contribute to Vim ecosystem 👍😄

**Comment by doums** [comment]
you are welcome
