### ISSUE TITLE
single quote or apostrophe

### ISSUE THREAD

**Issue by ghost** [doums/coBra#4]
How do I ignore the closing in a single quotes context?

If I write `there's a cat` it converts always to `there's' a cat` as it tries to close the single quote.

I've been trying to skip this behaviour with no success.
TIA

**Comment by doums** [comment]
Hi, I will no longer continue to maintain this plugin as I moved to neovim plus now I write my plugins in Lua. (Actually, I planned to rewrite it completely in lua and using treesitter queries, we'll see)
